### @name="get all products"
GET http://localhost:8080/api/products
Accept: application/json

### @name="get products by ID"
GET http://localhost:8080/api/products/4
Accept: application/json

### @name="add product"
POST http://localhost:8080/api/products
Accept: application/json
Content-Type: application/json

{
  "name": "Macbook Pro",
  "price": 287000.00,
  "quantity": 300
}

### @name="update product"
PUT http://localhost:8080/api/products/3
Accept: application/json
Content-Type: application/json

{
  "price": 8731.33
}

### @name="get products by Range"
GET http://localhost:8080/api/products?low=500&high=50000
Accept: application/json

